/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosTiendasOnlineRouteImport } from './routes/servicios/tiendas-online'
import { Route as ServiciosLandingPagesRouteImport } from './routes/servicios/landing-pages'
import { Route as ServiciosDesarrolloWebRouteImport } from './routes/servicios/desarrollo-web'
import { Route as ParaTiendasRouteImport } from './routes/para/tiendas'
import { Route as ParaRestaurantesRouteImport } from './routes/para/restaurantes'
import { Route as ParaInmobiliariasRouteImport } from './routes/para/inmobiliarias'
import { Route as ParaClinicasRouteImport } from './routes/para/clinicas'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosTiendasOnlineRoute = ServiciosTiendasOnlineRouteImport.update({
  id: '/servicios/tiendas-online',
  path: '/servicios/tiendas-online',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosLandingPagesRoute = ServiciosLandingPagesRouteImport.update({
  id: '/servicios/landing-pages',
  path: '/servicios/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosDesarrolloWebRoute = ServiciosDesarrolloWebRouteImport.update({
  id: '/servicios/desarrollo-web',
  path: '/servicios/desarrollo-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaTiendasRoute = ParaTiendasRouteImport.update({
  id: '/para/tiendas',
  path: '/para/tiendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaRestaurantesRoute = ParaRestaurantesRouteImport.update({
  id: '/para/restaurantes',
  path: '/para/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaInmobiliariasRoute = ParaInmobiliariasRouteImport.update({
  id: '/para/inmobiliarias',
  path: '/para/inmobiliarias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaClinicasRoute = ParaClinicasRouteImport.update({
  id: '/para/clinicas',
  path: '/para/clinicas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/para/clinicas': typeof ParaClinicasRoute
  '/para/inmobiliarias': typeof ParaInmobiliariasRoute
  '/para/restaurantes': typeof ParaRestaurantesRoute
  '/para/tiendas': typeof ParaTiendasRoute
  '/servicios/desarrollo-web': typeof ServiciosDesarrolloWebRoute
  '/servicios/landing-pages': typeof ServiciosLandingPagesRoute
  '/servicios/tiendas-online': typeof ServiciosTiendasOnlineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/para/clinicas': typeof ParaClinicasRoute
  '/para/inmobiliarias': typeof ParaInmobiliariasRoute
  '/para/restaurantes': typeof ParaRestaurantesRoute
  '/para/tiendas': typeof ParaTiendasRoute
  '/servicios/desarrollo-web': typeof ServiciosDesarrolloWebRoute
  '/servicios/landing-pages': typeof ServiciosLandingPagesRoute
  '/servicios/tiendas-online': typeof ServiciosTiendasOnlineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/para/clinicas': typeof ParaClinicasRoute
  '/para/inmobiliarias': typeof ParaInmobiliariasRoute
  '/para/restaurantes': typeof ParaRestaurantesRoute
  '/para/tiendas': typeof ParaTiendasRoute
  '/servicios/desarrollo-web': typeof ServiciosDesarrolloWebRoute
  '/servicios/landing-pages': typeof ServiciosLandingPagesRoute
  '/servicios/tiendas-online': typeof ServiciosTiendasOnlineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/para/clinicas'
    | '/para/inmobiliarias'
    | '/para/restaurantes'
    | '/para/tiendas'
    | '/servicios/desarrollo-web'
    | '/servicios/landing-pages'
    | '/servicios/tiendas-online'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/para/clinicas'
    | '/para/inmobiliarias'
    | '/para/restaurantes'
    | '/para/tiendas'
    | '/servicios/desarrollo-web'
    | '/servicios/landing-pages'
    | '/servicios/tiendas-online'
  id:
    | '__root__'
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/para/clinicas'
    | '/para/inmobiliarias'
    | '/para/restaurantes'
    | '/para/tiendas'
    | '/servicios/desarrollo-web'
    | '/servicios/landing-pages'
    | '/servicios/tiendas-online'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  ParaClinicasRoute: typeof ParaClinicasRoute
  ParaInmobiliariasRoute: typeof ParaInmobiliariasRoute
  ParaRestaurantesRoute: typeof ParaRestaurantesRoute
  ParaTiendasRoute: typeof ParaTiendasRoute
  ServiciosDesarrolloWebRoute: typeof ServiciosDesarrolloWebRoute
  ServiciosLandingPagesRoute: typeof ServiciosLandingPagesRoute
  ServiciosTiendasOnlineRoute: typeof ServiciosTiendasOnlineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/tiendas-online': {
      id: '/servicios/tiendas-online'
      path: '/servicios/tiendas-online'
      fullPath: '/servicios/tiendas-online'
      preLoaderRoute: typeof ServiciosTiendasOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/landing-pages': {
      id: '/servicios/landing-pages'
      path: '/servicios/landing-pages'
      fullPath: '/servicios/landing-pages'
      preLoaderRoute: typeof ServiciosLandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/desarrollo-web': {
      id: '/servicios/desarrollo-web'
      path: '/servicios/desarrollo-web'
      fullPath: '/servicios/desarrollo-web'
      preLoaderRoute: typeof ServiciosDesarrolloWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/tiendas': {
      id: '/para/tiendas'
      path: '/para/tiendas'
      fullPath: '/para/tiendas'
      preLoaderRoute: typeof ParaTiendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/restaurantes': {
      id: '/para/restaurantes'
      path: '/para/restaurantes'
      fullPath: '/para/restaurantes'
      preLoaderRoute: typeof ParaRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/inmobiliarias': {
      id: '/para/inmobiliarias'
      path: '/para/inmobiliarias'
      fullPath: '/para/inmobiliarias'
      preLoaderRoute: typeof ParaInmobiliariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/clinicas': {
      id: '/para/clinicas'
      path: '/para/clinicas'
      fullPath: '/para/clinicas'
      preLoaderRoute: typeof ParaClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  ParaClinicasRoute: ParaClinicasRoute,
  ParaInmobiliariasRoute: ParaInmobiliariasRoute,
  ParaRestaurantesRoute: ParaRestaurantesRoute,
  ParaTiendasRoute: ParaTiendasRoute,
  ServiciosDesarrolloWebRoute: ServiciosDesarrolloWebRoute,
  ServiciosLandingPagesRoute: ServiciosLandingPagesRoute,
  ServiciosTiendasOnlineRoute: ServiciosTiendasOnlineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
